name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - uses: actions/checkout@v4

      # prevents Dubious Ownership err
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +777 ./gradlew
        # CHANGE THIS TO DIRECTORY PATH
        working-directory: ./Team-3749-2025

      # Runs a single command using the runners shell
      - name: Compile and run tests on robot code
        run: ./gradlew build
      # CHANGE THIS TO DIRECTORY PATH
      working-directory: ./Team-3749-2025
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build robot code
        run: ./gradlew build
